
modLoader="javafml" #mandatory
loaderVersion="[4,)"
license="MIT License"
issueTrackerURL="https://github.com/sangeeeee/Better-Foliage/issues" #optional
[[mods]] #mandatory
modId="betterfoliage" #mandatory
version="${modVersion}" #mandatory
displayName="Better Foliage Reborn" #mandatory
displayURL="https://github.com/sangeeeee/Better-Foliage" #optional
logoFile="logo.png" #optional
credits="Paint_Ninja for the commission" #optional
authors="EERussianguy, PaintNinja" #optional
displayTest="IGNORE_ALL_VERSION"
description='''
Better Foliage Reborn enhances foliage with shallow-water reeds, snowy leaf fluff,
floating cherry petals, Iris shader animation, and expanded mod compatibility.

A fork of Better Foliage Renewed, based on the original Better Foliage.
Many visual features can be customized through resource packs.
'''
[[mixins]]
config="betterfoliage.mixins.json"
[[dependencies.betterfoliage]]
    modId="minecraft"
    type = "optional"
    versionRange="[1.21, 1.22)"
    ordering="NONE"
    side="BOTH"
[[dependencies.betterfoliage]]
    modId="biomesoplenty"
    type = "optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.betterfoliage]]
    modId="quark"
    type = "optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.betterfoliage]]
    modId="atmospheric"
    type = "optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.betterfoliage]]
    modId="tfc"
    type = "optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.betterfoliage]]
    modId="sodiumleafculling"
    type = "optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="CLIENT"
[[dependencies.betterfoliage]]
    modId="eclipticseasons"
    type = "optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="CLIENT"
