
modLoader="javafml" #mandatory
loaderVersion="[4,)"
license="MIT License"
issueTrackerURL="https://github.com/eerussianguy/Better-Foliage/issues" #optional
[[mods]] #mandatory
modId="betterfoliage" #mandatory
displayName="Better Foliage" #mandatory
displayURL="https://github.com/eerussianguy/Better-Foliage" #optional
logoFile="examplemod.png" #optional
credits="Paint_Ninja for the commission" #optional
authors="EERussianguy, PaintNinja" #optional
displayTest="IGNORE_ALL_VERSION"
description='''
A slim port of Better Foliage for 1.16 and beyond.

Most changes are configurable via resource pack.
'''
[[mixins]]
config="betterfoliage.mixins.json"
[[dependencies.betterfoliage]]
    modId="minecraft"
    type = "optional"
    versionRange="[1.21, 1.22)"
    ordering="NONE"
    side="BOTH"
[[dependencies.betterfoliage]]
    modId="biomesoplenty"
    type = "optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.betterfoliage]]
    modId="quark"
    type = "optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.betterfoliage]]
    modId="atmospheric"
    type = "optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.betterfoliage]]
    modId="tfc"
    type = "optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
